# Generated by Django 4.1.4 on 2023-01-05 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assemblies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=255)),
                ('assembly', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Assemblies',
            },
        ),
        migrations.CreateModel(
            name='Districts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Districts',
            },
        ),
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=50)),
                ('otp', models.CharField(max_length=5)),
                ('expiry', models.DateTimeField()),
            ],
            options={
                'db_table': 'Otp',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=255)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('whatsapp', models.CharField(max_length=255)),
                ('profession', models.CharField(blank=True, max_length=255, null=True)),
                ('district', models.CharField(max_length=255)),
                ('assembly', models.CharField(max_length=255)),
                ('village', models.CharField(max_length=255)),
                ('pincode', models.PositiveIntegerField()),
                ('role', models.CharField(max_length=255)),
                ('verified', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='PadayatraRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('padayatra_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admins.padayatraschedule')),
            ],
            options={
                'db_table': 'PadayatraRegistration',
            },
        ),
    ]
