# Generated by Django 4.1.4 on 2023-01-05 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='padayatraregistration',
            table='Padayatra_Registration',
        ),
    ]
