# Generated by Django 4.1.4 on 2023-01-05 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_padayatraregistration_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='districts',
            name='source_link',
            field=models.TextField(default=''),
        ),
    ]
