# Generated by Django 4.1.4 on 2023-01-12 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_districts_source_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='village',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
