# Generated by Django 4.1.4 on 2023-01-19 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_profession'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profession',
            new_name='Professions',
        ),
        migrations.AlterModelTable(
            name='professions',
            table='Professions',
        ),
    ]
