# Generated by Django 4.1.4 on 2023-01-21 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_rename_profession_professions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='referral_code',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
