# Generated by Django 4.1.4 on 2023-01-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_users_referral_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='blocked_posts',
            field=models.TextField(blank=True, null=True),
        ),
    ]
