# Generated by Django 4.1.4 on 2023-01-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_users_blocked_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='blocked_posts',
            field=models.TextField(default=''),
        ),
    ]
