# Generated by Django 4.1.4 on 2023-01-05 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Admins',
            },
        ),
        migrations.CreateModel(
            name='PadayatraSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('district', models.CharField(max_length=255)),
                ('assembly', models.CharField(max_length=255)),
                ('village', models.CharField(blank=True, max_length=255)),
                ('start_point', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(max_length=100)),
                ('registered_users_count', models.PositiveBigIntegerField(default=0)),
                ('registered_users', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'Padayatra_Schedule',
            },
        ),
    ]
