# Generated by Django 4.1.1 on 2022-12-26 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admins',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admins',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admins',
            name='is_supervisor',
            field=models.BooleanField(default=False),
        ),
    ]
