# Generated by Django 4.1.4 on 2023-01-06 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admins', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='padayatraschedule',
            name='registered_users',
        ),
    ]
