# Generated by Django 4.1.1 on 2022-12-26 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admins', '0002_admins_is_manager_admins_is_superuser_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admins',
            old_name='is_superuser',
            new_name='is_superadmin',
        ),
    ]
