# Generated by Django 4.1.4 on 2023-01-08 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admins', '0002_remove_padayatraschedule_registered_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='admins',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admins',
            name='is_superadmin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admins',
            name='is_supervisor',
            field=models.BooleanField(default=False),
        ),
    ]
