# Generated by Django 4.1.4 on 2023-01-12 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admins', '0003_admins_is_manager_admins_is_superadmin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='padayatraschedule',
            name='registered_users',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='padayatraschedule',
            name='source_link',
            field=models.TextField(default=''),
        ),
    ]
