# Generated by Django 4.1.4 on 2023-01-23 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admins', '0004_padayatraschedule_registered_users_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeURLs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live_url', models.TextField(blank=True, null=True)),
                ('Addational_Video_url1', models.TextField(blank=True, null=True)),
                ('Addational_Video_url2', models.TextField(blank=True, null=True)),
                ('Addational_Video_url3', models.TextField(blank=True, null=True)),
                ('Addational_Video_url4', models.TextField(blank=True, null=True)),
                ('Addational_Video_url5', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'YoutubeURLs',
            },
        ),
    ]
