# Generated by Django 4.1.4 on 2023-02-16 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admins', '0005_youtubeurls'),
    ]

    operations = [
        migrations.AddField(
            model_name='padayatraschedule',
            name='padayatra_link',
            field=models.TextField(default=''),
        ),
    ]
