# Generated by Django 4.1.4 on 2023-01-19 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Polls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_english', models.TextField()),
                ('options_english', models.JSONField(default=dict)),
                ('question_telugu', models.TextField()),
                ('options_telugu', models.JSONField(default=dict)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('polled_users', models.JSONField(default=dict)),
                ('published', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Polls',
            },
        ),
    ]
