# Generated by Django 4.1.4 on 2023-01-21 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feed', '0002_polls'),
    ]

    operations = [
        migrations.AddField(
            model_name='polls',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='polls',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='polls',
            name='thoughts',
            field=models.JSONField(default=dict),
        ),
    ]
