# Generated by Django 4.1.4 on 2023-01-24 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feed', '0004_posts_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='stories',
            name='thumbnail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
