# Generated by Django 4.1.4 on 2023-01-24 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feed', '0005_stories_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='blocked',
        ),
        migrations.AddField(
            model_name='comments',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
